# -*- coding: utf-8 -*-
"""svd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16LTDPQQ7dNanXd6pBAHXmj__2uf-gAcY
"""

import numpy as np
import scipy 
from scipy import linalg
import pprint as pp

M = [[1,2],[2,1],[3,4],[4,3]]
M = np.asarray(M)

svd = linalg.svd(M,full_matrices=False)

U = svd[0]
print("U:")
pp.pprint(U)

sigma = svd[1]
print("Sigma:")
pp.pprint(sigma)

V_T = svd[2]
print("V transpose:")
pp.pprint(V_T)

matrix = np.matmul(M.T,M)
Evals,Evecs = scipy.linalg.eigh(matrix)

Evals = sorted(Evals, reverse=True)
print("Evals:")
pp.pprint(Evals)
print("*****************")

Evecs = np.flip(Evecs,1)
print("Evecs:")
pp.pprint(Evecs)

